logging:
  config: classpath:logback-spring.xml    
  
server:
  port: 8080
  
spring:
  profiles:
    active: dev
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:file:~/routing
     username: sa
     password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
    