server:
  port: 8080
  
spring:
  profiles:
    active: dev
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:file:~/test
     username: sa
     password:
  jpa:
    show-sql: true
    